spring:
  data:
    mongodb:
      uri: mongodb://user1:group3password@bflinn-docdb.cluster-c4eqo06kg56i.us-east-1.docdb.amazonaws.com:27017/?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: taxPrepSystem
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 653928261139-q9dm9oml81rqufab4ufgvetjri78b2ji.apps.googleusercontent.com
            clientSecret: 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

javax:
  net:
    ssl:
      trustStore: /tmp/certs/rds-truststore.jks
      trustStorePassword: group3password
