spring:
  data:
    mongodb:
      uri: mongodb://user1:group3password@bflinn-docdb.cluster-c4eqo06kg56i.us-east-1.docdb.amazonaws.com:27017/?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: taxPrepSystem
  output:
    ansi:
      enabled: ALWAYS

javax:
  net:
    ssl:
      trustStore: /tmp/certs/rds-truststore.jks
      trustStorePassword: group3password
