spring:
  datasource:
    url: jdbc:h2:mem:taxdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
