import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

export type W2 = {
    social? : number,
    emp_tin : number,
    employer : string,
    wages : number,
    fed_withheld : number,
}

export const w2Api = createApi({
    reducerPath : 'w2Api',
    baseQuery : fetchBaseQuery({ baseUrl : 'http://localhost:8080/W2s'}),
    endpoints : (builder) => ({
        findAllW2s: builder.query<W2[], void>({
            query: () => '/',
        }),

        findW2BySocial: builder.query<W2, number>({
            query: (social) => `/W2/${social}`,
        }),

        createW2: builder.mutation<W2, W2>({
            query: (newW2) => ({
                method: 'POST',
                url: '/W2',
                body: newW2,
            }),
        }),

        updateW2: builder.mutation<W2, W2>({
            query: (updatedW2) => ({
                method: 'PUT',
                url: '/W2',
                body: updatedW2,
            }),
        }),

        deleteW2: builder.mutation<void, W2>({
            query: (w2ToDelete) => ({
                method: 'DELETE',
                url: '/W2',
                body: w2ToDelete,
            }),
        }),
    })
});

// Export hooks generated by createApi
export const { useFindAllW2sQuery, useFindW2BySocialQuery, useCreateW2Mutation, useUpdateW2Mutation, useDeleteW2Mutation } = w2Api;